### ISSUE TITLE
Organisation du projet

### ISSUE THREAD

**Issue by TheoVerhelst** [TheoVerhelst/BougeTaCaisse#1]
Faut mettre au point le travail à effectuer, ce que je vois déjà :
* Une classe qui représente une situation possible.
* Une classe qui va lire les fichiers d'entrée, et écrire les fichiers de sortie, et qui renverra/prendra en paramètre une instance de la classe ci-dessus, plus divers autres infos (voir énoncé)
* Une classe qui traite la structure de donnée et qui effectue l'algo efficace
* Peut-être une classe pour représenter le graphe, si jamais c'est plus simple que avec une matrice

Chaque nœud du graphe sera donc du même type que la valeur renvoyée par la classe de lecture/écriture.

Sachant que moi j'aurais moins de mal à faire la classe de lecture/écriture, t'en penses quoi ?

**Comment by RobinPetit** [comment]
Ok pour les points 1 et 2. Pour le point 4, je vois effectivement une classe Graphe et donc pour le 3, je verrais plus la résolution comme étant dans les méthodes de la classe Graphe.

On a donc quoi comme classe ? Pour l'instant :

```
Graphe, IO, Situation.
```

**Comment by TheoVerhelst** [comment]
Je mettrais `GestionnaireEntreeSortie`, ou `EntreeSortieFichier` (rah, le français) plutôt que `IO`, ou alors si vraiment ça te dérange un nom explicite `ES`, parce que `IO` c'est quand même de l'anglais ^^

**Comment by RobinPetit** [comment]
`GestionnaireES` me paraît être un bon compromis :D

**Comment by TheoVerhelst** [comment]
Enfait l'arbre peut etre utile si on génère les solutions par backtracking, et que on fait le truc de référencer vers un noeud du graphe préexistant si ils représent la même situation.

Par exemple si on a déjà un chemin vers une solution, que ce chemin est relativement long, et que en commençant un autre chemin on trouve que on arrive vers le milieu du chemin long en quelques déplacements seulement, alors on peut arrêter la et on a trouvé une nouvelle solution 2 fois plus rapide (de toute façon en y réfléchissant ça serait tout à fait inutile de continuer après ce moment-là).

On aurait donc un réseau qu'avec un sens graphique certain on peut comparer à un réseau de lianes qui tombent vers les solutions et qui s'entrecroisent en chemin.

Les objets Situation stockeraient donc la matrice du parking directement, pas des mouvement relatifs aux autres Situations, ce qui permet de parcourir une seule fois le graphe par insertion de noeud (dit comme ça c'est plutôt lol).

Ça augmente la complexité en `O(n)` mais ça permet donc d'éviter pas mal de génération de branches inutiles. Est-ce que c'est une réponse aux questions qu'on se posait mercredi ou bien je suis trop fatigué et on avait déjà conclu que c'était pas une solution utile ?

**Comment by RobinPetit** [comment]
J'y vois semi-clair aussi. Donc on en rediscute demain avec des petits schémas et des petits dessins de graphes tout mignons pour voir si c'est bien ça ?

**Comment by TheoVerhelst** [comment]
On avait juste pas dit que on pouvait s'arrêter de chercher quand on retombait sur une situation préexistante, on a donc pas remarqué que c'était une optimisation certaine. Mais oui on en reparle demain.

**Comment by TheoVerhelst** [comment]
On va donc appliquer l'algo de Dijkstra sur un graphe en hachant les situations au moment de la création, avec un HashSet. 
L'assistant a dit que il n'y avait qu'une voiture Goal, et une seule sortie, toujours à la même position,
ce qui simplifie vachement le bousin.
Je me dévoue pour faire la classe Situation, si t'as pas déja commencé :)

**Comment by RobinPetit** [comment]
Non je ne l'ai pas commencée, je te laisse faire. Pour la représentation du graphe, on fait comment ? Une classe arête et tout le bordel ou juste une matrice d'incidence avec des références vers les situations ?

**Comment by TheoVerhelst** [comment]
Étant donné que les arrêtes n'ont pas de label, une matrice d'incidence me parait bien. On pourrait aussi associer à chaque situation un indice genre `HashMap<Situation, int>` comme ça la matrice d'incidence est juste une liste de liste de booléens (qui devra être dynamique).

**Comment by RobinPetit** [comment]
Ça me semble être une bonne idée en effet.
