### ISSUE TITLE
Mouvements possibles 

### ISSUE THREAD

**Issue by TheoVerhelst** [TheoVerhelst/BougeTaCaisse#2]
C'est normal que dans la fonction de tests crée une voiture avec comme positions `{(1, 3), (2, 3),  (3, 3)}` et que les mouvements possibles soient `Up,  Down` ? À priori ça devrait donner quelque chose du genre :
```
+--+--+--+--+--+
¦  ¦  ¦  ¦  ¦  ¦
+--+--+--+--+--+
¦  ¦  ¦  ¦  ¦  ¦
+--+--+--+--+--+
¦  ¦  ¦  ¦  ¦  ¦
+--+--+--+--+--+
¦  ¦× ¦× ¦× ¦  ¦
+--+--+--+--+--+
¦  ¦  ¦  ¦  ¦  ¦
+--+--+--+--+--+
```

**Comment by RobinPetit** [comment]
C'est précisément ce sur quoi je bosse depuis une heure ^^

**Comment by RobinPetit** [comment]
[Fix'd](https://github.com/TheoVerhelst/BougeTaCaisse/commit/4da7a88d73a50670374b2a6901c62eae516e8312)
