### ISSUE TITLE
Algorithme principal

### ISSUE THREAD

**Issue by TheoVerhelst** [TheoVerhelst/BougeTaCaisse#3]
On a donc deux choix pour solve() :
* on génère tout le graphe, et on fait Dijkstra dessus
* on fait un parcours en largeur avec un élagage basé sur les techniques du stack de voitures bloquantes au moment de parcourir la liste des adjacents

Le premier aura une meilleure solution, mais peut être long si la grille est peu remplie. 
Le second sera très rapide, et on s'arrête à la première solution.

Exhaustivité ou rapidité ? (par rapport au but du cours, du projet, etc...)

**Comment by RobinPetit** [comment]
Je propose qu'on implémente d'abord la seconde et que si on est chaud, on implémente également la première (pour donner **également** la possibilité d'exhaustivité).

**Comment by RobinPetit** [comment]
C'est donc le parcours en largeur qui a été choisi, je ferme.
