### ISSUE TITLE
Derniers détails 

### ISSUE THREAD

**Issue by TheoVerhelst** [TheoVerhelst/BougeTaCaisse#4]
Si on a le temps, il y a deux choses que je vois qu'on peut faire pour parfaire le code :
 - [x] Réorganiser l'ordre des méthodes pour mettre celles publiques en premier, et avoir quelque chose de lisible. C'est le foutoir la classe `Situation` ^^
 - [ ] Les retours de fonctions qui sont du type `List<>` devraient renvoyer le type concret utilisé. Dans la plupart des cas ça change rien, dans le reste c'est mieux (plus de méthodes, genre `clone()`  etc)

**Comment by RobinPetit** [comment]
Ajouté à *plus tard* ^^

**Comment by RobinPetit** [comment]
C'en est où cette issue ? On la fait ou on la ferme ?

**Comment by TheoVerhelst** [comment]
je vais essayer de la faire

**Comment by RobinPetit** [comment]
Ok

**Comment by TheoVerhelst** [comment]
Voilà, pour moi tout est bon, tu peux imprimer le rapport. Le code faut le rendre sur l'UV, mais sur nos deux compte en même temps alors je suppose ?

**Comment by RobinPetit** [comment]
Je suppose qu'il faut effectivement le rendre tous les deux selon la nomenclature dans l'énoncé.
