### ISSUE TITLE
Problème de mémorisation des mouvements lors de la génération

### ISSUE THREAD

**Issue by RobinPetit** [TheoVerhelst/BougeTaCaisse#5]
Pendant la résolution, tous les mouvements testés sont enregistrés pour la solution finale. Or il ne faudrait enregistrer que les mouvements menant à a solution.

Actuellement, 109 mouvements sont enregistrés alors que seuls 5 ou 6 devraient apparaître.

**Comment by TheoVerhelst** [comment]
aaah, c'est ca les 109 ^^ oui c'est normal, I'll fix it.
