### ISSUE TITLE
Output en fichiers

### ISSUE THREAD

**Issue by RobinPetit** [TheoVerhelst/BougeTaCaisse#6]
Si j'ai bien compris l'énoncé, il ne faut pas avoir deux fichiers d'*outuput* mais uniquement un seul et ce, dans le cas où on ne trouve aucune solution. Tu saurais me dire où tu as vu que c'était deux fichiers ?

**Comment by TheoVerhelst** [comment]
Dans les premières lignes de l'énoncé:
>L'algorithme doit produire :
> * un ficher qui représente la situation initiale (voir Figure 1);
> * la séquence des déplacements de la voiture Goal;
> * un fichier qui représente la situation finale et la liste des déplacements de la voiture Goal et des autres voiture (voir Figure 3);
